providers = ["python"]

[phases.build]
cmds = [
    "uv run python manage.py collectstatic --noinput"
]

[start]
cmd = "uv run python manage.py migrate && uv run gunicorn aperture.wsgi:application --bind 0.0.0.0:8000 --workers 3"