# Generated by Django 6.0.4 on 2026-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Aperture Estate', max_length=80)),
                ('tagline', models.CharField(default="Curating the world's most significant architectural achievements for the discerning few.", max_length=240)),
                ('hq_address', models.CharField(default='14 Bruton Place, Mayfair, London, W1J 6LY', max_length=240)),
                ('email', models.EmailField(default='concierge@apertureestate.com', max_length=254)),
                ('phone', models.CharField(default='+44 (0) 20 7946 0123', max_length=40)),
                ('established_year', models.PositiveIntegerField(default=1984)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('photo_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
